spring:
  application:
    name: funds-es
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: localhost:9300
      repositories:
          enabled: true

server:
 port: 8089